@startuml Third-party API
participant "Scheduler" as S
participant "Third-party API" as TAPI
participant "Our API" as OAPI
participant "Database" as DB

S -> TAPI: Request product data
TAPI -> S: Return product data
S -> OAPI: Send product data
OAPI -> DB: Merge product data
DB -> OAPI: Confirmation
OAPI -> S: Confirmation
@enduml